// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBamVKrJFkmEpMEKJs1K-9QbIiwWsdwWIU',
    appId: '1:773921508363:web:c10e9a978f981616fecb0e',
    messagingSenderId: '773921508363',
    projectId: 'testing-c0b52',
    authDomain: 'testing-c0b52.firebaseapp.com',
    storageBucket: 'testing-c0b52.appspot.com',
    measurementId: 'G-746NBCH80H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXjV7GE5n8m3L2F8moY3dvi2TYdDinb3o',
    appId: '1:773921508363:android:ead64850ece861effecb0e',
    messagingSenderId: '773921508363',
    projectId: 'testing-c0b52',
    storageBucket: 'testing-c0b52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB165_uu3d-vIsXe_A9AXXpyj-j5KR9E8',
    appId: '1:773921508363:ios:63109ab4cfbbc39ffecb0e',
    messagingSenderId: '773921508363',
    projectId: 'testing-c0b52',
    storageBucket: 'testing-c0b52.appspot.com',
    iosBundleId: 'com.example.testing2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB165_uu3d-vIsXe_A9AXXpyj-j5KR9E8',
    appId: '1:773921508363:ios:0115399f6606dbb7fecb0e',
    messagingSenderId: '773921508363',
    projectId: 'testing-c0b52',
    storageBucket: 'testing-c0b52.appspot.com',
    iosBundleId: 'com.example.testing2.RunnerTests',
  );
}
